services:
  db:
    image: postgres:15
    container_name: odoo-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo19-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:19
    container_name: odoo-web
    depends_on:
      - db
    restart: always
    ports:
      - "8079:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo19-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo

volumes:
  odoo19-web-data:
  odoo19-db-data: