# Imagen base oficial
FROM odoo:19

# Cambiar a root para instalar dependencias
USER root

# Instalar dependencias adicionales si las necesitas
RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copiar addons personalizados
COPY ./addons /mnt/extra-addons

# Ajustar permisos
RUN chown -R odoo:odoo /mnt/extra-addons

# Volver al usuario odoo
USER odoo

# Puerto por defecto de Odoo
EXPOSE 8069