[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$ASDk3Ls3RgiBkDKm1HqPUQ$MRsFUkEj3szXbXahDF/FEMv/FwB3DwDJ0En2m54SjdzAHq2JD644KpiMj8KcA./cncPCPrvnGXRoAlBOaS9./Q

