[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
<<<<<<< HEAD
admin_passwd = Wilkins122009
=======
admin_passwd = admin123
>>>>>>> 9b20841fbda8274bac4f2d75f013286081fa82aa
